name: keirin
description: "A Flutter project for fixed gear community setups."
publish_to: 'none'
version: 1.0.0+1

environment:
  # Исправлена версия SDK на актуальную
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  google_fonts: ^8.2.1
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 # Немного понизил, 6.0.0 может требовать Dart 3.6+

flutter:
  uses-material-design: true